spring:
    profiles:
        active: local
    datasource:
        url: jdbc:h2:tcp://localhost/~/board
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                #                show_sql: true
                format_sql: true
                user_sql_comment: true
logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


jwt:
    secret: APPLE!@#$BANANA!@#$PINEAPPLE!@#$
    issuer: js.lee