spring:
    profiles:
        active: local
    datasource:
        url: jdbc:h2:tcp://localhost/~/board
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                #                show_sql: true
                format_sql: true
                user_sql_comment: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


jwt:
    secret: APPLE!@#$BANANA!@#$PINEAPPLE!@#$

file:
    dir: /Users/js/Desktop/file/
